server:
  port: 9001
  tomcat:
    connection-timeout: 2
    keep-alive-timeout: 15
    threads:
      max: 5
      min-spare: 1
  shutdown: graceful
book:
  greeting: Welcome to the local book catalog!
  envtest: Welcome to from yml
spring:
  application:
    name: catalog-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  lifecycle:
    timeout-per-shutdown-phase: 15s
management:
  endpoints:
    web:
      exposure:
        include: refresh